server:
  port: 9292
  max-http-header-size: 18432
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@10.0.130.84:1521:orcl
          username: BIUSER
          password: GMfr2020
        uat:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@10.0.130.27:1521:orcl
          username: BIUSER
          password: GMfr2020


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idel: 0
    timeout: 10000
mybatis:
  #  # spring boot集成mybatis的方式打印sql
  #  configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging.config:
  classpath:log4j2.xml

platform:
  es:
    schema: http
    host: 10.0.132.12
    port: 9200

local:
  schema: http
  host: localhost
  port: 9001

interfaceIssued:
  schema: http
  ip: 10.0.132.12
  port: 9292